#pragma checksum "WMainMenu.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "49221B8803A888024C8B79658C91F517905FD471"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace CSharpMaze {
    
    
    /// <summary>
    /// WMainMenu
    /// </summary>
    public partial class WMainMenu : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 48 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas PlayerRoom;
        
        #line default
        #line hidden
        
        
        #line 53 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridMainMenu;
        
        #line default
        #line hidden
        
        
        #line 54 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image ImgStartGame;
        
        #line default
        #line hidden
        
        
        #line 55 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image ImgLoadGame;
        
        #line default
        #line hidden
        
        
        #line 56 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image ImgSettingsGame;
        
        #line default
        #line hidden
        
        
        #line 57 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image ImgAboutGame;
        
        #line default
        #line hidden
        
        
        #line 58 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image ImgExitGame;
        
        #line default
        #line hidden
        
        
        #line 60 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridLoadGame;
        
        #line default
        #line hidden
        
        
        #line 65 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton RdGameOne;
        
        #line default
        #line hidden
        
        
        #line 66 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton RdGameTwo;
        
        #line default
        #line hidden
        
        
        #line 67 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton RdGameThree;
        
        #line default
        #line hidden
        
        
        #line 68 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SaveLoad;
        
        #line default
        #line hidden
        
        
        #line 69 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnBack;
        
        #line default
        #line hidden
        
        
        #line 71 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridSettings;
        
        #line default
        #line hidden
        
        
        #line 73 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MediaElement BackGroundMusic;
        
        #line default
        #line hidden
        
        
        #line 74 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider SldVolume;
        
        #line default
        #line hidden
        
        
        #line 77 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rdEasy;
        
        #line default
        #line hidden
        
        
        #line 78 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rdMedium;
        
        #line default
        #line hidden
        
        
        #line 79 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rdHard;
        
        #line default
        #line hidden
        
        
        #line 81 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnSaveSettings;
        
        #line default
        #line hidden
        
        
        #line 82 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnDefault;
        
        #line default
        #line hidden
        
        
        #line 85 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridHelp;
        
        #line default
        #line hidden
        
        
        #line 86 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txbHowToPlay;
        
        #line default
        #line hidden
        
        
        #line 88 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnBackHelp;
        
        #line default
        #line hidden
        
        
        #line 91 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridLost;
        
        #line default
        #line hidden
        
        
        #line 92 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txbDisplay;
        
        #line default
        #line hidden
        
        
        #line 93 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnMainMenu;
        
        #line default
        #line hidden
        
        
        #line 96 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridWin;
        
        #line default
        #line hidden
        
        
        #line 97 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txbWin;
        
        #line default
        #line hidden
        
        
        #line 98 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnMainMenuWin;
        
        #line default
        #line hidden
        
        
        #line 101 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridNewGame;
        
        #line default
        #line hidden
        
        
        #line 104 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbEasy;
        
        #line default
        #line hidden
        
        
        #line 105 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbMedium;
        
        #line default
        #line hidden
        
        
        #line 106 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbHard;
        
        #line default
        #line hidden
        
        
        #line 107 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnNewGame;
        
        #line default
        #line hidden
        
        
        #line 108 "WMainMenu.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnBackNewGame;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/CSharpMaze;component/wmainmenu.xaml", System.UriKind.Relative);
            
            #line 1 "WMainMenu.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 10 "WMainMenu.xaml"
            ((CSharpMaze.WMainMenu)(target)).Closing += new System.ComponentModel.CancelEventHandler(this.WMainMenu_OnClosing);
            
            #line default
            #line hidden
            return;
            case 2:
            this.PlayerRoom = ((System.Windows.Controls.Canvas)(target));
            return;
            case 3:
            this.GridMainMenu = ((System.Windows.Controls.Grid)(target));
            return;
            case 4:
            this.ImgStartGame = ((System.Windows.Controls.Image)(target));
            
            #line 54 "WMainMenu.xaml"
            this.ImgStartGame.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.ImgStartGame_MouseDown);
            
            #line default
            #line hidden
            
            #line 54 "WMainMenu.xaml"
            this.ImgStartGame.MouseEnter += new System.Windows.Input.MouseEventHandler(this.ImgStartGame_MouseEnter);
            
            #line default
            #line hidden
            
            #line 54 "WMainMenu.xaml"
            this.ImgStartGame.MouseLeave += new System.Windows.Input.MouseEventHandler(this.ImgStartGame_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 5:
            this.ImgLoadGame = ((System.Windows.Controls.Image)(target));
            
            #line 55 "WMainMenu.xaml"
            this.ImgLoadGame.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.ImgLoadGame_MouseDown);
            
            #line default
            #line hidden
            
            #line 55 "WMainMenu.xaml"
            this.ImgLoadGame.MouseEnter += new System.Windows.Input.MouseEventHandler(this.ImgLoadGame_MouseEnter);
            
            #line default
            #line hidden
            
            #line 55 "WMainMenu.xaml"
            this.ImgLoadGame.MouseLeave += new System.Windows.Input.MouseEventHandler(this.ImgLoadGame_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 6:
            this.ImgSettingsGame = ((System.Windows.Controls.Image)(target));
            
            #line 56 "WMainMenu.xaml"
            this.ImgSettingsGame.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.ImgSettingsGame_MouseDown);
            
            #line default
            #line hidden
            
            #line 56 "WMainMenu.xaml"
            this.ImgSettingsGame.MouseEnter += new System.Windows.Input.MouseEventHandler(this.ImgSettingsGame_MouseEnter);
            
            #line default
            #line hidden
            
            #line 56 "WMainMenu.xaml"
            this.ImgSettingsGame.MouseLeave += new System.Windows.Input.MouseEventHandler(this.ImgSettingsGame_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 7:
            this.ImgAboutGame = ((System.Windows.Controls.Image)(target));
            
            #line 57 "WMainMenu.xaml"
            this.ImgAboutGame.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.ImgAboutGame_MouseDown);
            
            #line default
            #line hidden
            
            #line 57 "WMainMenu.xaml"
            this.ImgAboutGame.MouseEnter += new System.Windows.Input.MouseEventHandler(this.ImgAboutGame_MouseEnter);
            
            #line default
            #line hidden
            
            #line 57 "WMainMenu.xaml"
            this.ImgAboutGame.MouseLeave += new System.Windows.Input.MouseEventHandler(this.ImgAboutGame_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 8:
            this.ImgExitGame = ((System.Windows.Controls.Image)(target));
            
            #line 58 "WMainMenu.xaml"
            this.ImgExitGame.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.ImgExitGame_MouseDown);
            
            #line default
            #line hidden
            
            #line 58 "WMainMenu.xaml"
            this.ImgExitGame.MouseEnter += new System.Windows.Input.MouseEventHandler(this.ImgExitGame_MouseEnter);
            
            #line default
            #line hidden
            
            #line 58 "WMainMenu.xaml"
            this.ImgExitGame.MouseLeave += new System.Windows.Input.MouseEventHandler(this.ImgExitGame_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 9:
            this.GridLoadGame = ((System.Windows.Controls.Grid)(target));
            return;
            case 10:
            this.RdGameOne = ((System.Windows.Controls.RadioButton)(target));
            
            #line 65 "WMainMenu.xaml"
            this.RdGameOne.Checked += new System.Windows.RoutedEventHandler(this.RdGameOne_OnChecked);
            
            #line default
            #line hidden
            return;
            case 11:
            this.RdGameTwo = ((System.Windows.Controls.RadioButton)(target));
            
            #line 66 "WMainMenu.xaml"
            this.RdGameTwo.Checked += new System.Windows.RoutedEventHandler(this.RdGameTwo_OnChecked);
            
            #line default
            #line hidden
            return;
            case 12:
            this.RdGameThree = ((System.Windows.Controls.RadioButton)(target));
            
            #line 67 "WMainMenu.xaml"
            this.RdGameThree.Checked += new System.Windows.RoutedEventHandler(this.RdGameThree_OnChecked);
            
            #line default
            #line hidden
            return;
            case 13:
            this.SaveLoad = ((System.Windows.Controls.Button)(target));
            
            #line 68 "WMainMenu.xaml"
            this.SaveLoad.Click += new System.Windows.RoutedEventHandler(this.SaveLoad_OnClick);
            
            #line default
            #line hidden
            return;
            case 14:
            this.BtnBack = ((System.Windows.Controls.Button)(target));
            
            #line 69 "WMainMenu.xaml"
            this.BtnBack.Click += new System.Windows.RoutedEventHandler(this.BtnBackHelp_Click);
            
            #line default
            #line hidden
            return;
            case 15:
            this.GridSettings = ((System.Windows.Controls.Grid)(target));
            return;
            case 16:
            this.BackGroundMusic = ((System.Windows.Controls.MediaElement)(target));
            
            #line 73 "WMainMenu.xaml"
            this.BackGroundMusic.MediaEnded += new System.Windows.RoutedEventHandler(this.BackGroundMusic_OnMediaEnded);
            
            #line default
            #line hidden
            return;
            case 17:
            this.SldVolume = ((System.Windows.Controls.Slider)(target));
            
            #line 74 "WMainMenu.xaml"
            this.SldVolume.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.SldVolume_OnValueChanged);
            
            #line default
            #line hidden
            return;
            case 18:
            this.rdEasy = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 19:
            this.rdMedium = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 20:
            this.rdHard = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 21:
            this.BtnSaveSettings = ((System.Windows.Controls.Button)(target));
            
            #line 81 "WMainMenu.xaml"
            this.BtnSaveSettings.Click += new System.Windows.RoutedEventHandler(this.BtnSaveSettings_Click);
            
            #line default
            #line hidden
            return;
            case 22:
            this.BtnDefault = ((System.Windows.Controls.Button)(target));
            
            #line 82 "WMainMenu.xaml"
            this.BtnDefault.Click += new System.Windows.RoutedEventHandler(this.BtnDefault_Click);
            
            #line default
            #line hidden
            return;
            case 23:
            this.GridHelp = ((System.Windows.Controls.Grid)(target));
            return;
            case 24:
            this.txbHowToPlay = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 25:
            this.BtnBackHelp = ((System.Windows.Controls.Button)(target));
            
            #line 88 "WMainMenu.xaml"
            this.BtnBackHelp.Click += new System.Windows.RoutedEventHandler(this.BtnBackHelp_Click);
            
            #line default
            #line hidden
            return;
            case 26:
            this.GridLost = ((System.Windows.Controls.Grid)(target));
            return;
            case 27:
            this.txbDisplay = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 28:
            this.BtnMainMenu = ((System.Windows.Controls.Button)(target));
            
            #line 93 "WMainMenu.xaml"
            this.BtnMainMenu.Click += new System.Windows.RoutedEventHandler(this.BtnMainMenu_Click);
            
            #line default
            #line hidden
            return;
            case 29:
            this.GridWin = ((System.Windows.Controls.Grid)(target));
            return;
            case 30:
            this.txbWin = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 31:
            this.BtnMainMenuWin = ((System.Windows.Controls.Button)(target));
            
            #line 98 "WMainMenu.xaml"
            this.BtnMainMenuWin.Click += new System.Windows.RoutedEventHandler(this.BtnMainMenu_Click);
            
            #line default
            #line hidden
            return;
            case 32:
            this.GridNewGame = ((System.Windows.Controls.Grid)(target));
            return;
            case 33:
            this.rbEasy = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 34:
            this.rbMedium = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 35:
            this.rbHard = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 36:
            this.BtnNewGame = ((System.Windows.Controls.Button)(target));
            
            #line 107 "WMainMenu.xaml"
            this.BtnNewGame.Click += new System.Windows.RoutedEventHandler(this.BtnNewGame_OnClick);
            
            #line default
            #line hidden
            return;
            case 37:
            this.BtnBackNewGame = ((System.Windows.Controls.Button)(target));
            
            #line 108 "WMainMenu.xaml"
            this.BtnBackNewGame.Click += new System.Windows.RoutedEventHandler(this.BtnBackNewGame_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

